openapi: 3.0.3
info:
  title: OpenAPI 3.0 TEST
  description: Open API 3.0 Test
  termsOfService: http://swagger.io/terms/
  contact:
    email: rhsnqk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://
tags:
  - name: product
    description: product 관련 API
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /products:
    get:
      tags:
        - product
      summary: product 조회 API
      description: 상태에 따른 product 조회
      operationId: findProductsByStatus
      parameters:
        - name: status
          in: query
          description: 상품을 살 수 있는지, 판매 완료 되었는지 상태
          required: false
          explode: true
          schema:
            type: string
            default: available
            enum:
              - available
              - soldout
      responses:
        '200':
          description: 상품 조회가 성공한 경우
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '400':
          description: 잘못된 요청
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        id: 1
        name: Table